baseURL: https://blog.auryn.dev/
title: Auryn's Blog
paginate: 15
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-Q2W252LSJR

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Auryn's Blog
    description: "This is a blog where I will share some information and knowledge"
    keywords: [Blog, Portfolio, PaperMod]
    author: Auryn Engel
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: false

    label:
        text: "Auryn's Blog"
        iconHeight: 35

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to my blog where I will share some information and knowledge

    socialIcons:
        - name: stackoverflow
          url: "https://stackoverflow.com/users/7927982/auryn31"
        - name: github
          url: "https://github.com/auryn31"
        - name: linkedin
          url: "https://www.linkedin.com/in/auryn-engel/"

    analytics:
        google:
            SiteVerificationTag: "4t21lUFHzcfilprtuN8GOOU_qzTDkZmxSOrvYCHBp08"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/auryn31/blog/tree/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

menu:
    main:
        - identifier: categories
          name: categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20
        - identifier: me
          name: me
          url: /about/
          weight: 30